import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1a1c1b",
        "secondary-fixed-dim": "#bacbb6",
        "on-background": "#1a1c1b",
        "secondary-fixed": "#d6e8d1",
        "on-primary": "#ffffff",
        "secondary-container": "#d6e8d1",
        "primary-fixed": "#c2eebf",
        "outline-variant": "#c2c8be",
        "on-secondary-fixed-variant": "#3b4b3a",
        error: "#ba1a1a",
        "tertiary-fixed": "#ffdad9",
        surface: "#f9f9f7",
        "primary-fixed-dim": "#a7d1a4",
        "surface-tint": "#416742",
        "surface-container-low": "#f4f4f2",
        "on-primary-fixed": "#002106",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9f7",
        "on-secondary-container": "#596957",
        "surface-container-high": "#e8e8e6",
        "tertiary-fixed-dim": "#ffb3b2",
        "on-tertiary-fixed-variant": "#6f3537",
        "tertiary-container": "#a36060",
        "surface-variant": "#e2e3e1",
        "primary-container": "#557c55",
        outline: "#727970",
        primary: "#3d633e",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#fff8f7",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#111f11",
        "surface-container-highest": "#e2e3e1",
        background: "#f9f9f7",
        "surface-dim": "#dadad8",
        "on-surface-variant": "#424940",
        "inverse-on-surface": "#f1f1ef",
        tertiary: "#864849",
        "inverse-primary": "#a7d1a4",
        secondary: "#536351",
        "on-tertiary-fixed": "#390b0e",
        "error-container": "#ffdad6",
        "surface-container": "#eeeeec",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#ecffe6",
        "inverse-surface": "#2f3130",
        "on-primary-fixed-variant": "#2a4f2c",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
